### ISSUE TITLE
File stat error with ftp-srv

### ISSUE THREAD

**Issue by JbIPS** [sergi/parse-listing#13]
Hi,

I'm using [ftp-srv](https://www.npmjs.com/package/ftp-srv) as a server and [jsftp](https://www.npmjs.com/package/jsftp) as a client in my tests and I saw my test using `JSFTP.ls()` returned no entry when calling it on a file.

After inspection I find out ftp-srv is outputing:
```
212 -rw-rw-rw- 1 1 1        16190 Dec 07 16:25
```
which is remove because it does not match `RE_MULTI` in `parser.js`, because of the space between the code and the first `-`. 

Is the solution to change `RE_MULTI` to `/^(\d\d\d)\s?-/` to allow space or did I miss something?

I can make a PR if you think this is a bug. Thank you

**Comment by sergi** [comment]
That should actually never happen, and it looks like it may be a bug in ftp-srv.

FTP responses always start with a code and a dash, unless it signals the end of a multiline response, in which case it will start with a code and space, but it would not include a line with a  file description. 

Check out "Response Format" in https://cr.yp.to/ftp/request.html, and look at how a standard file listing response should look in https://github.com/sergi/parse-listing/blob/master/test/parser.test.js#L639.

Does that make sense?

**Comment by JbIPS** [comment]
Thank you for your response. If it's standard, I'll open an issue in ftp-srv.
