### ISSUE TITLE
Error on files with accent (like é)

### ISSUE THREAD

**Issue by jmzoda** [sergi/parse-listing#6]
Hello,
The decoding of filenames with accents returns '\charcode' with many modules (grunt-ftpsync) using parse-listing. Please, could you take a look at utf8 module to decode filenames with accents?
Example : 
    else if (parsedEntry) {
      parsedEntry.name = utf8.decode(parsedEntry.name);  // <<< code to add + require(‘utf8’) on top of parser.js file
      parsed.push(parsedEntry);
    }
Just a proposal, don't hesitate...
Regards,
JMZ

**Comment by evanplaice** [comment]
evanplaice/node-ftpsync#9

**Comment by evanplaice** [comment]
Has this been corrected? If so, in what version?

evanplaice/node-ftpsync/issues/9
